# Generated by Django 5.0.3 on 2024-03-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_productmaterial_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(through='apps.ProductMaterial', to='apps.material'),
        ),
    ]
